import type { Metadata, Viewport } from 'next'
import './globals.css'

export const metadata: Metadata = {
  metadataBase: new URL('https://constructoradoma.cl'),
  title: 'Constructora DOMA | Construcción, remodelaciones y paisajismo en Concepción',
  description: 'Constructora DOMA ejecuta proyectos de construcción, remodelación, diseño, jardinería, paisajismo e instalación de cámaras en Concepción y San Pedro de la Paz.',
  keywords: [
    'constructora en Concepción',
    'constructora en San Pedro de la Paz',
    'empresa constructora San Pedro de la Paz',
    'arquitectura en San Pedro de la Paz',
    'remodelaciones en San Pedro de la Paz',
    'diseño de interiores San Pedro de la Paz',
    'paisajismo San Pedro de la Paz',
    'arquitectura en Concepción',
    'diseño de interiores en Concepción',
    'diseño de espacios Concepción',
    'remodelaciones en Concepción',
    'empresa de remodelaciones Concepción',
    'paisajismo en Concepción',
    'jardinería en Concepción',
    'diseño de jardines Concepción',
    'terminaciones de construcción Concepción',
    'diseño de espacios Concepción',
    'instalación de cámaras Concepción',
    'cámaras de seguridad Concepción',
    'remodelación de casas en Concepción',
    'interiorismo en Concepción Chile',
    'decoración de interiores Concepción',
    'diseño de ambientes Concepción',
    'arquitectura interior Concepción',
    'proyectos de remodelación Biobío',
    'constructora en Concepción',
    'construcción de casas en Concepción',
    'jardinería San Pedro de la Paz',
    'instalación de cámaras San Pedro de la Paz',
  ],
  authors: [{ name: 'Constructora DOMA' }],
  creator: 'Constructora DOMA',
  publisher: 'Constructora DOMA',
  alternates: { canonical: '/' },
  openGraph: {
    title: 'Constructora DOMA | Construcción, terminaciones y diseño en Concepción y San Pedro de la Paz',
    description: 'Construcción, remodelaciones, diseño, jardinería, paisajismo e instalación de cámaras en Concepción, San Pedro de la Paz y la Región del Biobío.',
    url: 'https://constructoradoma.cl',
    siteName: 'Constructora DOMA',
    locale: 'es_CL',
    type: 'website',
  },
  robots: { index: true, follow: true },
}
export const viewport: Viewport = { width: 'device-width', initialScale: 1, maximumScale: 1, themeColor: '#f4f2ed' }
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="es"><body>{children}</body></html> }
