export type CatalogEntry = {
  title: string
  category: string
  content: string
  metadata: Record<string, string>
}

export const domaCatalog: CatalogEntry[] = [
  { title: 'Rangos referenciales de construcción', category: 'precios', content: 'Rangos referenciales de mercado chileno para construcción: obra gruesa y construcción residencial desde $850.000 a $1.600.000 CLP por m². El valor depende de superficie, terreno, especificaciones, estructura, terminaciones y complejidad. No constituye una cotización.', metadata: { service: 'construcción', unit: 'm²', market: 'Chile', status: 'referencial' } },
  { title: 'Rangos referenciales de remodelación', category: 'precios', content: 'Rangos referenciales de mercado chileno para remodelación integral: desde $450.000 a $1.200.000 CLP por m². Remodelaciones parciales se evalúan según partidas, estado existente, materiales y alcance. No constituye una cotización.', metadata: { service: 'remodelación', unit: 'm²', market: 'Chile', status: 'referencial' } },
  { title: 'Rangos referenciales de terminaciones', category: 'precios', content: 'Rangos referenciales de mercado chileno para terminaciones: desde $180.000 a $650.000 CLP por m², según pavimentos, revestimientos, cielos, pintura, puertas, griferías, iluminación y nivel de especificación. No constituye una cotización.', metadata: { service: 'terminaciones', unit: 'm²', market: 'Chile', status: 'referencial' } },
  { title: 'Rangos referenciales de diseño e interiorismo', category: 'precios', content: 'Rangos referenciales para diseño de interiores e interiorismo en Chile: desde $12.000 a $35.000 CLP por m² para diseño y especificación, o proyectos desde $650.000 según alcance. La propuesta final depende de levantamiento, planos, visualizaciones y compras. No constituye una cotización.', metadata: { service: 'diseño e interiorismo', unit: 'm²', market: 'Chile', status: 'referencial' } },
  { title: 'Rangos referenciales de paisajismo', category: 'precios', content: 'Rangos referenciales para diseño y ejecución de paisajismo en Chile: diseño desde $8.000 a $25.000 CLP por m² y ejecución desde $45.000 a $180.000 CLP por m², según preparación de terreno, riego, especies, iluminación y materialidad. No constituye una cotización.', metadata: { service: 'paisajismo', unit: 'm²', market: 'Chile', status: 'referencial' } },
  { title: 'Rangos referenciales de seguridad y domótica', category: 'precios', content: 'Rangos referenciales para seguridad perimetral, cámaras y domótica en Chile: proyectos básicos desde $650.000, instalaciones integrales residenciales habitualmente entre $1.500.000 y $6.000.000 CLP. El valor depende de cantidad de puntos, canalización, equipos, automatizaciones, configuración y superficie. No constituye una cotización.', metadata: { service: 'seguridad y domótica', unit: 'proyecto', market: 'Chile', status: 'referencial' } },
  { title: 'Política de precios DOMA', category: 'precios', content: 'Los valores publicados son rangos referenciales de mercado chileno y no reemplazan una cotización DOMA. Para cotizar se requiere conocer ubicación, superficie, estado actual, planos o fotografías, alcance, materialidades y nivel de terminación. DOMA trabaja en Concepción, San Pedro de la Paz y la Región del Biobío. La visita y propuesta se coordinan por WhatsApp al +56 9 4454 4938.', metadata: { service: 'cotizaciones', market: 'Chile', status: 'referencial' } },
]
